[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project]
name = "__name__"
version = "0.1.0"

dependencies = [
    "numpy",
    "dash",
    "plotly",
    "matplotlib",
    "pandas",
]